language: python
sudo: false
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - CXX="g++-4.9" CC="gcc-4.9" CYTHON=1
before_install:
  - pip install --upgrade pip
  - pip install cython
install:
  - pip install .
script:
  - cd tests; nosetests
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9